### PR TITLE
New syntax highlight

### PR DESCRIPTION
**Pull request by glcraft**
# Improve syntax highlight by a new textmate grammar with more rules more precise.

image

image

image

Note there is stil some little parsing bugs (to be fair, textmate grammar is not the best way to parse a language).

### CODE REVIEW

**Comment by fdncred** [comment]
Wow, this is an epic PR! Thanks so much. 

Are all these changes hand tweaked? I have no problem accepting that if so, but I wonder if these changes can be built into the generate-patterns.nu script. It would be cool to generate this syntax automatically and would be helpful as language features get added like new commands and such. Let me know what you think and again, thanks so much!

I'll be playing with this shortly.

**Comment by fdncred** [comment]
Looks like there may be a few tweaks still needed. For instance, notice the 3 separate colors for `let` in this screenshot. Is that on purpose or do you consider that a bug?

image

**Comment by glcraft** [comment]
Hi there 👋 !

> Are all these changes hand tweaked? I have no problem accepting that if so, but I wonder if these changes can be built into the generate-patterns.nu script. It would be cool to generate this syntax automatically and would be helpful as language features get added like new commands and such. Let me know what you think and again, thanks so much!

~95% of the file were hand made. The only part that was generated are [builtin commands](https://github.com/nushell/vscode-nushell-lang/blob/204931b837f87730a50e52fa6105b4e4e5d0af80/syntaxes/nushell.tmLanguage.json#L408) and [keywords](https://github.com/nushell/vscode-nushell-lang/blob/204931b837f87730a50e52fa6105b4e4e5d0af80/syntaxes/nushell.tmLanguage.json#L109)
[I just made a program to generate optimal regex for that](https://github.com/glcraft/list-to-tree).

> Looks like there may be a few tweaks still needed. For instance, notice the 3 separate colors for let in this screenshot. Is that on purpose or do you consider that a bug?

Oh well, definitely a bug 😅 , I'll investigate this.

> I also think that we'd perhaps like all keywords to be one color, like let, def, etc, all nushell internal commands to be one color, external commands to be another color, all variables be one color, etc. Thoughts?

Well, the choice of the still was a bit complicated when I made this. I wanted to treat the language style like a programming language, more that a shell language. So actually, I made : 
* commands name (internal and external) are entity.name.function (appears in yellow in vscode dark+). I also specified builtin and external in the style.
* control keywords like if, while, break, *resulted from `$nu.scope.commands | where is_keyword == true`* are keyword.control (appears in purple in vscode dark+)
* most defining keywords (export, let, use, module, def) are keyword.other (appears in blue in vscode dark+)
* variables and fields are considered as variable (appears in cyan in vscode dark+)

I took the decision to make $nu and $env to be variable.language (appears in blue in vscode dark+, like keyword.other) but i don't know if it was a good idea.

So in the end, i'm not that far from what you said. Let me know if you want something different 😉 

Then about your last comment, as I said, I made the language style like a programming language, inspired by the convention of other text mate schema from other languages like C, C++, JS, and so on. 

Let take a look at the previous text mate you made : 
image

Here, variable, keywords and commands has the same color (blue on my theme). 
Also :

image

From the theming convention use by other tm language, `def` looks like function, `match-for-single` looks like type or namespace, and parameters looks like keywords. That's unconventional when you work with other language. 
So I wanted to get close to other language textmates convention by rearranging token by their real style. Do you see what I mean ?

**Comment by glcraft** [comment]
OK, The bug in your screenshot has been fixed

image

**Comment by fdncred** [comment]
I'm not sure why but I've been getting this error recently when trying to debug.
image
I'm also not getting any syntax highlighting at all. I'm not sure what is going on.

**Comment by fdncred** [comment]
I figured it out. I haven't run `vsce package` in a while. I needed to do that. This reminds me that other changes will be needed here like bumping the version in the package.json and adding information to the changelog.md.

**Comment by glcraft** [comment]
I don't know about that. 

I also got this message since I worked on the syntax but I didn't try to resolve nor touch anything related on. As you can see in the PR, only one file changed 😀

**Comment by fdncred** [comment]
Agreed, but we need to figure it out some how. I can't test anything on my mac and we can't release a plugin that doesn't work. I'll try and test sometime today on Windows to see if it makes any difference.

**Comment by fdncred** [comment]
It's broken in Windows too. The last commit that has coloring is [94df741](https://github.com/nushell/vscode-nushell-lang/pull/73/commits/94df741e8f00508ef9a04a8f3d05444d46aa7950). All the next commits after that, there is no syntax highlighting.

**Comment by glcraft** [comment]
Oh, coloring doesn't work since that commit, I didn't understand that earlier. It might be something I change indeed.

I can reproduce the issue, it's weird I did not see this before I push that. I going to check that

**Comment by glcraft** [comment]
I just resolve a bad syntax in a regex in the rule operators-word, I can now see the color. Can you test with that last commit please ?

**Comment by fdncred** [comment]
It's working again, yay!!!

Can you please outline what the colors are supposed to be? I'm having a hard time keeping up. For instance, export alias is blue but export def is yellow. I would think all the exports would be the same color. I think I'm fine with yellow here because def is yellow. What are your thoughts?

I'd really like to have some documented rules in a table like about these colorings (other than the regex) like. Not a requirement for this PR but I think it's a good thing to have, especially since I'm not sure how to test that everything is the proper color. I also think that this may help us negotiate more specifically if you (or someone else) prefers this word type to be a different color. What do you think about this?

| word type | tm scope | color |
| - | - | - |
| keywords | some scope | some color |
| internal commands | some scope | some color |
| variables | some scope | some color |

One thing is for sure. This latest commit makes the colors look 1000 % better. Great job!

Here's a bug i think. Line 20 `and` isn't colored.
image

**Comment by fdncred** [comment]
I created this because I'm loving these changes so much. :)

Left: Where we started. Right: Where we're at now.
syntax

**Comment by glcraft** [comment]
> Here's a bug i think. Line 20 and isn't colored.
For that one at least, that's not a bug 😀 . Default operators color is white. You can see at the bottom of the inspector that the foreground scope selected is "keyword.operator", which the color is "#D4D4D4"

> Can you please outline what the colors are supposed to be? I'm having a hard time keeping up. For instance, export alias is blue but export def is yellow. I would think all the exports would be the same color. I think I'm fine with yellow here because def is yellow. What are your thoughts?

Well, normally, colors doesn't matter. What matters is the scope name of token textmate find : `let` should be a "keyword.other.*", variables should be "variable.other.*" (`$nu` and `$env` *can* be "variable.language.*"), numbers should be "constant.numeric, strings should be "string.*" and so on.

That's what I tried to explain you : color is just a way to represent those scope names. When we say "This looks better in green" (in our vscode theme) we are currently bending the theme system to fit colors and not scope names.
Moreover, we should apply as same scope names from other language as possible to get an uniform and conventional way to read code whatever the language we are reading. With the vscode dark+ theme, people uses to know that green is for types, yellow are functions and "dark blue" keywords to take those examples.
If colors matter, what we should to do is a new theme that fit well with nushell scripts.

So I want to rethink about it : do you still want to use wrong scope name to fit colors on vscode dark+ theme, or we pass *the most* standard scope name as possible ?

Whatever you choose, there is no problem, but I want to be clear about that point 🙂

**Comment by fdncred** [comment]
> For that one at least, that's not a bug 😀 . Default operators color is white. You can see at the bottom of the inspector that the foreground scope selected is "keyword.operator", which the color is "#D4D4D4".

Ok, good. Let's make it another color other than white. Maybe magenta or another not-often-used color.

> So I want to rethink about it : do you still want to use wrong scope name to fit colors on vscode dark+ theme, or we pass the most standard scope name as possible ?

Let's stick with what we've got right now (except for the change I just requested) and we always have the opportunity to change it later.

**Comment by fdncred** [comment]
wow! what an awesome PR and so much back and forth testing. Thanks so much @glcraft!!!

**Pull request merged**
