### PR TITLE
fix go to definition on windows

### LINKED ISSUE #138: Going to definition prepends `\\` to the file path in Windows
When going to the definition of a user-defined command, the Windows path seems to not get parsed properly and the extension prepends `\\` to paths like so: `\\C:\foo\bar.nu` which then fails to open.

### PR DESCRIPTION
**Pull request by gaetschwartz**
Fixes #138

### CODE REVIEW

**Comment by fdncred** [comment]
oh, ya. that looks much better. thanks! i'll try to test and play with it later this afternoon!

**Comment by fdncred** [comment]
I don't have a problem landing this but I think it's pinpointed another bug. 
In this file, I can "Go To Definition" on line 40 with `get-target-dependencies` but I can't do it on line 58 for `find-deps`. There could be a bug in nushell or something else. If you have time, it would be a big help to figure out what's going on.

https://github.com/nushell/nu_scripts/blob/d48ce0b6c1ea1c4c531d9f4f37be9f51aa3672f4/make_release/nu_deps.nu#L58-L59

**Comment by gaetschwartz** [comment]
@fdncred Are you still experience this issue ? It works on my end ?


https://github.com/nushell/vscode-nushell-lang/assets/25441359/2b15357a-4714-47c4-8db5-913c9b8acd1e

**Comment by fdncred** [comment]
It's working now because i fixed the script. If you change the line to the way it was when I reported it `let deps = find-deps` it won't work. But if you make it `let deps = (find-deps)` it works fine. The first way is invalid nushell even though our validator doesn't detect it.

**Pull request merged**
