### PR TITLE
Updated syntax + fixed generation script

### PR DESCRIPTION
**Pull request by Yethal**
Commands with hyphens are now sorted before commands without which fixes coloring of commands such as group-by
Commands with single subcommands (each while, encode base64 etc) now have coloring generated

### CODE REVIEW

**Comment by Yethal** [comment]
@fdncred It's ready for review now

**Comment by Yethal** [comment]
Ok now it's working

**Comment by dandavison** [comment]
Nice! Here's a screenshot of what I see (v0.6.0 on the left, this branch on the right). E.g. I see that your branch is fixing some cases where arguments where highlighted as keywords / command names. E.g. in `ansi green` and `from table table`, the "green" and "table1" are black in your branch but blue in v0.6.0. I don't think I see a difference for `group-by`?


image

**Comment by fdncred** [comment]
@Yethal I went through all the example.nu with nushell theme in dark mode and all i have to say is wow!  Nice job fixing all the command highlighting with only script changes. Very nice!

Below are some TODOs, unrelated to this PR that we should probably think a little more about.
- We need to add these too as keywords
true
false

- I'd like to add all the ansi keywords like ansi green, ansi reset, etc and all `char` keywords like `char nl`

- I'm not sure why the quoting is messed up but it is. Maybe it's always been? Maybe it needs to be a sublanguage?
$"(ansi -e { fg: '#0000ff' bg: '#ff0000' attr: b })Hello Nu World(ansi reset)"

- Need to add these as numbers
0x7F and 0o7, 0x[1F FF AA AA]

- I'm wondering if we should be coloring dotted variables like
$db.b <-- should b be the same color as $db?
same for $env.FOO_ENV

- I'm wondering if parameters should be colored differently like `--trash`
I notice `--append` is colored wrong but that's because append is a keyword. So, maybe there should be a regex for these type of things.
Just like `-w` is all one color

- We need a regex for urls probably because they can get colored oddly

**Comment by dandavison** [comment]
> Another item I'm considering is removing the themes altogether - don't really like them

Yes the themes selector seem to be behaving slightly out-of-band with the rest of VSCode. I use light backgrounds, and it sort of forces me to select on of the nushell ones at extension install time, but I just end up re-selecting my normal theme using the main color themes selector once I'm out of the "extension install" window.

**Comment by fdncred** [comment]
@dandavison ya, I do the same thing. The one thing themes do provide is the ability to highlight items with much more granularity because we can make up our own names of keyword types. But I don't think it's helping anyone since it's implemented (by me) so kludgy. One day we'll have a LSP that can help with sematic coloring.

**Comment by fdncred** [comment]
let's land this, although i'm not sure if this is enough to make another release. it's really just making the syntax generation automated. correct me if I'm wrong and if you want to see another release because of this PR.

**Comment by Yethal** [comment]
@fdncred Changes in this PR do improve the syntax highlighting (by generating better patterns) so I'd say it does warrant a patch release of the plugin

**Comment by fdncred** [comment]
@Yethal it's broken again. With `let varname = blah` `varname` is not being highlighted correctly. I'm not sure if it's your changes or mine.

**Comment by fdncred** [comment]
oh, i just figured out what it is.  We need more changes.

If terms are mentioned below keywords.patterns branch, like in "variable", then we cannot use them in the keywords branch. Here's an example.
Right now `let varname = blah` doesn't highlight `varname` correctly. This is because it's listed here *BEFORE* `variable` below.
```
        {
          "name": "keyword.other.l",
          "match": "\\b(lowercase|load-env|let-env|length|ls-df|lines|limit|list|last|lit|let|ls)\\b"
        },
```
since it's above, it's not being colored below in this context.
```
    "variable":
    {
      "match": "(alias|let|let-env)\\s+[\\$'\"]?([a-z A-Z0-9_-]+)['\"]?|(\\$[a-zA-Z0-9_\\-]+)|(\\|)([$a-zA-Z0-9-]+)[\\s,]+([$a-zA-Z0-9-]+)(\\|)",
      "name": "variable.nushell",
      "captures":
      {
        "1":
        {
          "name": "keyword.other.nushell"
        },
        "2":
        {
          "name": "variable.name.nushell"
        },
...
```
The fix is to remove `let` from the keywords like this:
```
"match": "\\b(lowercase|load-env|let-env|length|ls-df|lines|limit|list|last|lit|ls)\\b"
```
Then variables are found and colored properly.

Maybe there's another way to do this, but I'm not sure what it is. It would be nice to have all our keywords listed like you have them without having to remove some because we declare them below.

**Comment by fdncred** [comment]
same for `alias`, `let`, `let-env`, `for`, `def`, `def-env`, `extern`

**Comment by fdncred** [comment]
I've manually tweaked the syntax in PR #63

**Pull request merged**
