### PR TITLE
Feature/update snippets

### PR DESCRIPTION
**Pull request by EmilySeville7cfg**
- [x] add snippets for almost all [commands](https://www.nushell.sh/commands/) before `fill`
- [x] add snippets for almost all data types
- [x] add snippets for some operators
- [x] explain snippet naming convention

Snippets should not just provide access for some things, but allow reminding some syntax.

### CODE REVIEW

**Comment by fdncred** [comment]
oh, nice! thanks so much for jumping in. this seems pretty useful!!!

**Comment by EmilySeville7cfg** [comment]
PR is ready for review.

**Comment by fdncred** [comment]
> @fdncred, do you think it worth to add snippets for sed, awk in future PRs even when Nushell coverts the most (maybe all) their functionality?

I'd prefer to keep the snippets nushell specific. I'm not sure I'd want to add snippets for a bunch of bash commands.

**Comment by EmilySeville7cfg** [comment]
> Wow, what a lot of work you've put into this. I'm just wondering if these snippets will conflict with the current ide completion functionality we just added? I'm going to test it out in a little while but was wondering what you thought.

I don't think they will complete for now. Snippets tend to provide command combinations, like in cases where data is read from stdin. AFAIK, LSP doesn't do that. But even when it will, we can just remove snippets and allow LSP provide better suggestions. For instance, what can be done: LSP can automatically insert pipe and placeholder for previous command if the next one reads from stdin (but just when there is nothing before). Snippets can't perform such analysis. ;)

**Comment by fdncred** [comment]
I finally got around to testing these. They're so cool!!! Thanks!

**Pull request merged**
