### PR TITLE
:sparkles: add `prettier` to dev deps

### LINKED ISSUE #180: Use `biomejs` or `prettier` to format
I was wondering if it would be welcome to add prettier or [biomejs ](https://biomejs.dev/)to the dependencies, and format the code.
I personally like biome more, because is more consistent and it has a linter much alike eslint, but the terminal is way better.

sample:
image

My intention is first to land one of these formatters and then to pull the changes to #117. What do you think?

### PR DESCRIPTION
**Pull request by AucaCoyan**
Fixes #180 

I left only the relevant changes. When this is reviewed and it's okay, I'll make one commit formatting everything.

As for configs I have:
- use `'` instead of default `"`
- end of line default: `lf`

### CODE REVIEW

**Comment by AucaCoyan** [comment]
I'll mark it ready for review, but don't merge it yet! (it's pending the format, which pollutes the review with a lot of changes)

**Comment by fdncred** [comment]
ok, lemme know when you're ready to land it.

**Comment by AucaCoyan** [comment]
Great! All the format passed and merged changes from main. Ready!

**Comment by fdncred** [comment]
Thanks

**Pull request merged**
