### PR TITLE
Add support for `def 'my-function'` syntax highlighting and add tests to it

### LINKED ISSUE #156: nu --ide-ast bugs
### Describe the bug

`nu --ide-ast` doesn't highlight some tokens properly
image

### How to reproduce

Create a .nu file with a content below and open it in vscode:

```
mkdir test; cd test # cd is not highlighted

def 'abc' [] {} # def and 'abc' are incorrect

def abcd [] {} # all is correct here
```

### Expected behavior

I expected nu to highlight `; cd`, and `def 'abc'` properly

### Screenshots

_No response_

### Configuration

| key                | value                                         |
| ------------------ | --------------------------------------------- |
| version            | 0.85.0                                        |
| branch             |                                               |
| commit_hash        |                                               |
| build_os           | macos-aarch64                                 |
| build_target       | aarch64-apple-darwin                          |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31)           |
| rust_channel       | stable-aarch64-apple-darwin                   |
| cargo_version      | cargo 1.70.0 (ec8a8a0ca 2023-04-25)           |
| build_time         | 2023-09-23 05:58:06 +00:00                    |
| build_rust_channel | release                                       |
| allocator          | mimalloc                                      |
| features           | dataframe, default, sqlite, trash, which, zip |
| installed_plugins  |                                               |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by AucaCoyan**
fixes #156 

The only caveat is the `--flag` after the name will be colored just like the function name

image

### CODE REVIEW

**Comment by AucaCoyan** [comment]
Hi! Does anyone have a little time to review this? 😄 Thanks!

**Comment by fdncred** [comment]
sorry, i'll try to look at it this week sometime.

**Comment by AucaCoyan** [comment]
No problem! We all have lots of `todo`s, take your time

**Comment by fdncred** [comment]
@AucaCoyan I spent some time looking at this today and I think the regex changes are not correct. We should be able to capture all groups and using the beginCaptures to highlight them individually. I don't think the groups are correct either.

**Comment by fdncred** [comment]
We may need @glcraft to help iron out this regex. This one below is close because it sees --env and --wrapped at the beginning or ending.

image

This is my regex and capture attempt below that doesn't work either because it's uses range 0,2 and therefore is not picking the correct capture names in all instances.
```json
    "function": {
      "begin": "(export)?(\\s+def)(\\s+--\\w+){0,2}(\\s+[\\w\\-]+|\\s+\"[\\w\\- ]+\")(\\s+--\\w+){0,2}",
      "beginCaptures": {
        "1": { "name": "entity.name.function.nushell" },
        "2": { "name": "entity.name.function.nushell" },
        "3": { "name": "entity.name.type.nushell" },
        "4": { "name": "entity.name.type.nushell" },
        "5": { "name": "entity.name.function.nushell" },
        "6": { "name": "entity.name.type.nushell" },
        "7": { "name": "entity.name.type.nushell" }
      },
```

**Comment by glcraft** [comment]
Hi
I agree with @fdncred, the regex you provided is incorrect, because it will accepts wrong syntaxes like the following : 
```
export def "my-function (...
export def "my-function' (...
export def my-function" (...
export def my function (...
```
I know that the textmate grammar is not a linter, but due to the huge number of rules present in this file, we have to be precise in the parsing so the good rules are used in the good place.

Now, my previous regex was indeed incomplete. it miss the single quotes function name syntax (and the back quotes too) and I went for one flag only whereas it can be several before and/or after the function name.

@fdncred attempt for matching several flags is good. It will parse the flags correctly. But I think we should set the number of occurence to 0 or more, in case nu syntax change and add more flags to def/Export def in the future. What do you think ?

I'm going to commit a change to the tmgrammar file.

**Comment by fdncred** [comment]
>  But I think we should set the number of occurence to 0 or more, in case nu syntax change and add more flags to def/Export def in the future. What do you think ?

I'm good with 0 or more.

> (oh, and sorry for the late about https://github.com/nushell/vscode-nushell-lang/issues/156, I saw it but I could not fix it at the time and forget about it later 😅)

No worries at all.

Thanks for all your input @glcraft

**Comment by glcraft** [comment]
Oh, it seems i cannot commit onto this PR branch 🤔

**Comment by AucaCoyan** [comment]
> Oh, it seems i cannot commit onto this PR branch 🤔

Thanks for the response! I added you as a collaborator in my fork, check if you can commit again

**Comment by glcraft** [comment]
Thanks, but no, I cannot. It says I don't have permission.

**Comment by AucaCoyan** [comment]
image
mmmmm
maybe did you received an email, perhaps?

**Comment by glcraft** [comment]
Yes you're right. I am able to push now, thanks :+1:

**Comment by AucaCoyan** [comment]
You are welcome! You are also helping me too :smile:

**Comment by fdncred** [comment]
Someone just ping me when this is ready to look at again.

**Comment by glcraft** [comment]
@fdncred I fixed and push the change of the tmgrammar file. Check by your side if it's good :+1:

**Comment by fdncred** [comment]
@glcraft I think this is much better and we can land it. It doesn't cover use case where --env or --wrapped are after the parameter declaration like this.
```nushell
export def --env my-function [] --wrapped {}
```

I need to check with the team if that's even supposed to be valid syntax. I think it's invalid because of this.
image

**Comment by fdncred** [comment]
Thanks!

**Pull request merged**
