### PR TITLE
Fix TextMate regex

### PR DESCRIPTION
**Pull request by glcraft**
From https://github.com/hustcer/nu-grammar/issues/1

Remove non-fixed text width in lookbehind and negative lookahead regex.

**Note:** about "command" rule regex, i didn't remember why I wrote `|(?<=\\)|\\}|\\]|\\$\\w+)\\.` in "command" rule. I think it was useful in early stage of making this file. 
Anyway, I didn't see any case where it is useful now. I tried different files to see if it causes any issue if I remove it, but I didn't see any. 
So if someone see something wrong in the future, let me now :+1:

### CODE REVIEW

**Comment by fdncred** [comment]
I'm not sure this is working right. Here is `variables`
image

I'm struggling to find something that will test the other changes.

**Comment by glcraft** [comment]
Argh yeah, that was the issue I was trying to avoid in command... I have to do something so

**Comment by fdncred** [comment]
I looked it over and tested it out. Nothing else seems to jump out. I did find a new issue though unrelated to this PR. https://github.com/nushell/vscode-nushell-lang/issues/139

**Comment by fdncred** [comment]
Thanks for all your help!

**Pull request merged**
